# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DataLoaderApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DataLoaderApp
  pod 'Alamofire', '~> 5.2'
  pod 'SnapKit', '~> 5.0.0'
  pod 'RealmSwift'
  
  target 'DataLoaderAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DataLoaderAppUITests' do
    # Pods for testing
  end

end
